/*<-----Cart.JS Are Stating Here */
import React from 'react';
import './Cart.css';

/* <----- React Font Awesome CDN ----->*/
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faMoneyBill, faUser } from '@fortawesome/free-solid-svg-icons';


const Cart = (props) => {
    /*<----- Destructuring Is Below ----->*/
    const { cart } = props;
    const totalSalary = cart.reduce((previous, current) => previous + current.salary, 0)
    return (
        /*<----- Cart Info Are Here ----->*/
        <div className="cart">
            {/* Icon Added Dynamically & Showing People & Total Sum in Numeric */}
            <h5 style={{ color: '#9575CD' }}><span><FontAwesomeIcon icon={faUser} /></span> Programmer Count: {cart.length}</h5>
            <h5 style={{ color: '#8D6E63' }}><span><FontAwesomeIcon icon={faMoneyBill} /></span> Programmer Fees: {totalSalary}</h5>

            {
                /* Mapping With Information of Programmer Data Generated By JSON */
                cart.map(info => <div className="addUser" key={info.id}>
                    <div className="cart-info">
                        <div className="cart-img">
                            <img className="w-100 rounded-circle" src={info.img} alt="" />
                        </div>
                        <div>
                            <h6><strong>Name: </strong>{info.name}</h6>
                            <p><strong>Email:</strong> {info.email}</p>
                        </div>
                    </div>
                </div>)
            }

        </div>
    );
};

export default Cart;
/*<-----Cart.JS Are Ending Here */